import type { DomainId, ScenarioId } from "@/types";

export interface DomainPack {
  id: DomainId;
  label: string;
  blurb: string;
  projectNames: string[];
  projectKeys: string[];
  epicTitles: string[];
  areas: string[]; // feature modules used in summaries
  storyCaps: string[]; // "capability" fragments
  storyBenefits: string[];
  userRoles: string[]; // for "As a X" stories
  bugSymptoms: string[];
  bugSurfaces: string[];
  bugConditions: string[];
  taskVerbs: string[];
  taskObjects: string[];
  labels: string[];
  commentSnippets: string[];
  sprintGoals: string[];
}

export const DOMAINS: Record<DomainId, DomainPack> = {
  fintech: {
    id: "fintech",
    label: "Fintech / Payments",
    blurb: "Ledgers, KYC, payouts and fraud tooling",
    projectNames: ["Atlas Pay", "Ledgerline", "Northstar Billing", "Vault Core"],
    projectKeys: ["PAY", "LDG", "BILL", "VLT"],
    epicTitles: [
      "Instant payouts GA",
      "KYC onboarding revamp",
      "Ledger reconciliation engine",
      "Fraud rules v2",
      "Open banking integrations",
      "Card tokenization",
      "Merchant settlement reports",
    ],
    areas: [
      "payment intent API",
      "settlement batch",
      "KYC document upload",
      "webhook delivery",
      "fraud scoring pipeline",
      "multi-currency wallet",
      "chargeback workflow",
      "statement exporter",
      "payout scheduler",
      "3DS2 challenge flow",
    ],
    storyCaps: [
      "retry failed payouts with exponential backoff",
      "verify identity documents via OCR",
      "expose balance snapshots through the reporting API",
      "flag transactions above dynamic risk thresholds",
      "support SEPA Instant credit transfers",
      "reconcile PSP settlements against the ledger nightly",
      "let merchants configure webhook retry policies",
      "mask PAN data in all log sinks",
    ],
    storyBenefits: [
      "we stay PCI-DSS compliant",
      "finance can close the books without manual exports",
      "merchants stop filing support tickets",
      "we reduce payout failure rates below 0.5%",
      "auditors get a complete trail",
      "ops can replay settlements safely",
    ],
    userRoles: ["merchant admin", "finance ops analyst", "compliance officer", "platform integrator"],
    bugSymptoms: [
      "Intermittent 502 from",
      "Duplicate entries created by",
      "Rounding error (±0.01) in",
      "Timeout after 30s on",
      "Stale cache in",
      "Webhook signature mismatch on",
    ],
    bugSurfaces: [
      "/v1/payouts",
      "/v1/charges/{id}/refund",
      "settlement-worker",
      "kyc-webhook consumer",
      "ledger-posting service",
      "fraud-scorer gRPC handler",
    ],
    bugConditions: [
      "amount exceeds 10k in a single currency",
      "Idempotency-Key header is reused after 24h",
      "two webhooks arrive within the same second",
      "the merchant has a pending KYC review",
      "FX rate refreshes mid-transaction",
      "batch runs across a DST boundary",
    ],
    taskVerbs: ["Rotate", "Backfill", "Audit", "Tune", "Document", "Migrate", "Decommission"],
    taskObjects: [
      "PSP sandbox credentials",
      "settlement ledger partitions",
      "KYC retention policy",
      "webhook delivery dashboards",
      "risk rule thresholds",
      "PCI scope inventory",
    ],
    labels: ["pci-scope", "ledger", "kyc", "fraud", "payouts", "webhooks", "compliance", "fx"],
    commentSnippets: [
      "Replayed the failed settlement batch in staging — diff looks clean.",
      "Compliance signed off, removing the hold label.",
      "This reproduces only when the PSP sandbox rate-limits us.",
      "Checked the ledger journal: the duplicate posting predates the fix.",
      "Can we add a metric before this ships? Finance will ask for it.",
      "Pairing with risk team on the threshold values tomorrow.",
    ],
    sprintGoals: [
      "Ship instant payouts behind the feature flag",
      "Burn down KYC onboarding blockers",
      "Stabilize settlement reconciliation",
    ],
  },

  ecommerce: {
    id: "ecommerce",
    label: "E-commerce",
    blurb: "Storefront, checkout, catalog and fulfilment",
    projectNames: ["Cartwave", "Storefront X", "Fulfil Hub", "Catalog One"],
    projectKeys: ["SHOP", "CART", "FUL", "CAT"],
    epicTitles: [
      "One-page checkout",
      "Promotions engine",
      "Inventory sync 2.0",
      "Mobile storefront parity",
      "Returns self-service",
      "Search relevance boost",
      "Subscriptions pilot",
    ],
    areas: [
      "checkout funnel",
      "product detail page",
      "cart drawer",
      "promo code service",
      "inventory reservation",
      "order tracking page",
      "returns portal",
      "recommendation carousel",
      "gift card balance",
      "address autocomplete",
    ],
    storyCaps: [
      "let guests check out without creating an account",
      "stack percentage and fixed-amount promo codes",
      "reserve inventory for 15 minutes during checkout",
      "show delivery estimates from the carrier API",
      "support buy-online-pickup-in-store",
      "send back-in-stock notifications",
      "render size guides on apparel PDPs",
      "localize prices for EU storefronts",
    ],
    storyBenefits: [
      "we cut cart abandonment",
      "support tickets about returns drop",
      "marketing can run campaigns without engineering",
      "mobile conversion catches up with desktop",
      "we stop overselling low-stock SKUs",
    ],
    userRoles: ["shopper", "merchandiser", "support agent", "warehouse manager"],
    bugSymptoms: [
      "404 on",
      "Price mismatch between",
      "Infinite spinner on",
      "Duplicate line items in",
      "Broken images on",
      "Wrong tax rate applied in",
    ],
    bugSurfaces: [
      "checkout/payment step",
      "PDP variant picker",
      "cart-drawer",
      "promo-engine rule evaluator",
      "order-confirmation email",
      "search autocomplete",
    ],
    bugConditions: [
      "a promo code expires mid-session",
      "cart contains both subscription and one-off items",
      "user switches currency after adding items",
      "inventory hits zero during checkout",
      "browser is Safari with ITP enabled",
    ],
    taskVerbs: ["A/B test", "Merchandise", "Load-test", "Localize", "Audit", "Clean up"],
    taskObjects: [
      "checkout funnel events",
      "Q4 landing pages",
      "promo rules from the legacy engine",
      "PDP structured data",
      "carrier rate tables",
      "sitemap and canonical tags",
    ],
    labels: ["checkout", "pdp", "promo", "inventory", "search", "mobile", "seo", "returns"],
    commentSnippets: [
      "Verified on the staging storefront — promo stacking works as specced.",
      "Merch team confirmed the copy, moving to review.",
      "This only reproduces with the legacy promo engine disabled.",
      "Checked GA: checkout drop-off at this step is 12% so the fix matters.",
      "Design approved the empty-state illustration.",
    ],
    sprintGoals: ["Get one-page checkout to internal beta", "Clear the promo-engine backlog"],
  },

  healthcare: {
    id: "healthcare",
    label: "Healthcare",
    blurb: "Patient portal, scheduling and clinical workflows",
    projectNames: ["Carepoint", "MediSchedule", "Chartwell", "Pulse Portal"],
    projectKeys: ["CARE", "MED", "CHRT", "PLS"],
    epicTitles: [
      "Patient self-scheduling",
      "EHR integration (FHIR)",
      "Telehealth waiting room",
      "E-prescription renewal flow",
      "Clinical notes templates",
      "Billing & claims status",
    ],
    areas: [
      "appointment scheduler",
      "patient intake form",
      "FHIR resource mapper",
      "telehealth lobby",
      "eRx renewal queue",
      "care-team messaging",
      "lab results viewer",
      "insurance eligibility check",
    ],
    storyCaps: [
      "let patients reschedule appointments up to 24h ahead",
      "map FHIR Observation resources to the results viewer",
      "notify care teams when a patient joins the telehealth lobby",
      "route eRx renewals to the on-call provider",
      "surface allergy alerts during prescribing",
      "verify insurance eligibility in real time",
      "support proxy access for parents of minors",
    ],
    storyBenefits: [
      "front-desk call volume drops",
      "providers spend less time on admin",
      "we stay HIPAA compliant",
      "patients stop missing lab results",
      "claims get rejected less often",
    ],
    userRoles: ["patient", "front-desk coordinator", "provider", "billing specialist"],
    bugSymptoms: [
      "PHI visible in",
      "Wrong timezone shown in",
      "Sync failure between",
      "Session timeout ignored by",
      "Duplicate appointments from",
      "Missing audit log entry in",
    ],
    bugSurfaces: [
      "scheduler calendar view",
      "FHIR DocumentReference import",
      "telehealth lobby",
      "eligibility-check widget",
      "intake PDF renderer",
    ],
    bugConditions: [
      "patient has two active insurance policies",
      "appointment crosses a DST boundary",
      "provider has back-to-back telehealth sessions",
      "intake form is resumed after 7 days",
      "the EHR sandbox returns a 429",
    ],
    taskVerbs: ["Audit", "Anonymize", "Document", "Validate", "Rotate", "Review"],
    taskObjects: [
      "PHI access logs",
      "FHIR mapping spreadsheets",
      "consent form versions",
      "BAA inventory",
      "retention schedules",
      "screen-reader flow for the portal",
    ],
    labels: ["hipaa", "fhir", "scheduling", "telehealth", "erx", "accessibility", "billing"],
    commentSnippets: [
      "Compliance review done — no PHI in the new log lines.",
      "Tested against the EHR sandbox; mapping doc updated.",
      "Accessibility pass found two focus-trap issues, filing separately.",
      "Confirmed with the clinic pilot group that the flow matches their playbook.",
    ],
    sprintGoals: ["Pilot self-scheduling with two clinics", "Close out FHIR R4 mapping gaps"],
  },

  devtools: {
    id: "devtools",
    label: "Dev Tools / SaaS",
    blurb: "APIs, SDKs, CI pipelines and dashboards",
    projectNames: ["Forge API", "Pipeliner", "Telemetry Kit", "DevDash"],
    projectKeys: ["API", "CI", "TEL", "DASH"],
    epicTitles: [
      "Usage-based billing meter",
      "SDK v3 release",
      "Pipeline caching layer",
      "Public status page",
      "SSO / SCIM provisioning",
      "Audit log streaming",
      "Terraform provider",
    ],
    areas: [
      "REST API v2",
      "TypeScript SDK",
      "pipeline runner",
      "artifact cache",
      "usage metering service",
      "webhooks console",
      "org settings page",
      "audit log stream",
      "CLI auth flow",
    ],
    storyCaps: [
      "meter API calls per workspace with minute granularity",
      "add retry-with-jitter to the SDK HTTP client",
      "cache pipeline layers by content hash",
      "stream audit events to customer S3 buckets",
      "support SCIM group push from Okta",
      "version the API with sunset headers",
      "generate SDK reference docs from OpenAPI",
      "expose p95 latency per endpoint in the dashboard",
    ],
    storyBenefits: [
      "enterprise deals stop blocking on SSO",
      "customers can self-serve incident comms",
      "build times drop below the 5-minute mark",
      "support can answer usage questions without engineering",
      "we can deprecate v1 endpoints safely",
    ],
    userRoles: ["platform engineer", "workspace admin", "DevOps lead", "integration developer"],
    bugSymptoms: [
      "429s not retried by",
      "Memory leak in",
      "Race condition in",
      "Flaky test in",
      "Incorrect deprecation header from",
      "Clock skew errors on",
    ],
    bugSurfaces: [
      "pipeline-runner",
      "sdk-typescript retry logic",
      "usage-aggregator",
      "artifact-cache eviction",
      "SCIM provisioning job",
      "webhook dispatcher",
    ],
    bugConditions: [
      "workspace exceeds 10k requests/min",
      "two runners claim the same cache key",
      "token refresh happens mid-request",
      "S3 bucket policy denies multipart uploads",
      "system clock drifts more than 5 minutes",
    ],
    taskVerbs: ["Load-test", "Deprecate", "Benchmark", "Document", "Rotate", "Instrument"],
    taskObjects: [
      "v1 REST endpoints",
      "SDK changelog",
      "runner AMI images",
      "API error catalog",
      "signing keys",
      "OpenAPI spec examples",
    ],
    labels: ["api", "sdk", "ci", "sso", "billing", "performance", "docs", "security"],
    commentSnippets: [
      "Benchmarked: p99 dropped from 840ms to 210ms after the cache fix.",
      "This is a breaking change — needs a migration guide before release.",
      "Repro confirmed with a 3-node runner pool.",
      "Docs PR is up, linking it here.",
      "Security reviewed the token scope change, all good.",
    ],
    sprintGoals: ["Cut SDK v3 RC.2", "Prove cache hit-rate above 80%"],
  },

  gaming: {
    id: "gaming",
    label: "Gaming Studio",
    blurb: "Live-ops, matchmaking, economy and content",
    projectNames: ["Project Ember", "LiveOps Central", "Nexus Arena", "Starforge"],
    projectKeys: ["EMB", "LIVE", "ARENA", "STAR"],
    epicTitles: [
      "Season 7 battle pass",
      "Matchmaking rating rework",
      "Anti-cheat wave 3",
      "Player housing beta",
      "Cross-play parties",
      "In-game events framework",
      "Economy inflation controls",
    ],
    areas: [
      "matchmaking service",
      "battle pass track",
      "friend invite flow",
      "guild system",
      "cosmetic shop",
      "replay viewer",
      "server browser",
      "chat moderation tools",
      "daily quest generator",
    ],
    storyCaps: [
      "gracefully degrade matchmaking when regions are underpopulated",
      "let players gift battle pass tiers",
      "support cross-platform party voice",
      "rate-limit shop purchases to fight gold sellers",
      "add spectate mode to custom lobbies",
      "run time-limited double-XP events from live config",
      "detect and shadow-ban aim-bot signatures",
    ],
    storyBenefits: [
      "queue times stay under 90 seconds",
      "economy inflation stays within tolerance",
      "players stop dodging cross-play",
      "live-ops can run events without a client patch",
      "churn in the first session drops",
    ],
    userRoles: ["player", "live-ops producer", "community manager", "economy designer"],
    bugSymptoms: [
      "Desync in",
      "Crash (GPU hang) in",
      "Rubber-banding on",
      "Exploit allowing",
      "Missing localization in",
      "Duplicate rewards from",
    ],
    bugSurfaces: [
      "replay viewer timeline scrubbing",
      "battle pass tier claim",
      "cross-play party invites",
      "guild bank deposits",
      "daily quest rollover",
    ],
    bugConditions: [
      "server tick drops below 20Hz",
      "player migrates hosts mid-match",
      "two daily quests complete simultaneously",
      "locale is set to pt-BR",
      "region failover happens during claim",
    ],
    taskVerbs: ["Tune", "Playtest", "Localize", "Balance", "Backfill", "Profile"],
    taskObjects: [
      "MMR decay parameters",
      "Season 7 reward track",
      "economy faucets and sinks",
      "server tick profiler captures",
      "PT-BR string table",
      "bot difficulty curve",
    ],
    labels: ["liveops", "matchmaking", "economy", "antichat", "ux", "crash", "exploit", "loc"],
    commentSnippets: [
      "Playtest sign-off done on the new lobby flow.",
      "Repro rate is ~1 in 40 matches with high ping — keeping priority.",
      "Economy sim shows faucet/sink delta back within 2%.",
      "Live config flag is wired, we can ship without a patch.",
    ],
    sprintGoals: ["Lock Season 7 reward track", "Prove MMR rework in the playtest env"],
  },

  logistics: {
    id: "logistics",
    label: "Logistics / Fleet",
    blurb: "Routing, tracking, dispatch and warehouse ops",
    projectNames: ["RouteIQ", "Dockwise", "ParcelTrack", "FleetLink"],
    projectKeys: ["RTE", "DOCK", "PCL", "FLT"],
    epicTitles: [
      "Dynamic re-routing",
      "Driver mobile app offline mode",
      "Warehouse wave planning",
      "Customer delivery ETA page",
      "Carrier rate shopping",
      "Cold-chain telemetry",
    ],
    areas: [
      "route optimizer",
      "driver manifest",
      "proof-of-delivery capture",
      "dock scheduler",
      "ETA prediction model",
      "parcel scan events",
      "temperature sensor ingest",
      "fuel card reconciliation",
    ],
    storyCaps: [
      "re-route drivers around incidents within 60 seconds",
      "cache manifests for 12h of offline driving",
      "capture photo + signature proof of delivery",
      "publish customer-facing ETAs from the prediction model",
      "compare carrier rates at label purchase time",
      "alert when reefer temperature leaves the 2–8°C band",
      "batch wave plans by dock door availability",
    ],
    storyBenefits: [
      "dispatchers stop re-planning by hand",
      "WISMO tickets drop",
      "drivers in dead zones stay productive",
      "spoilage claims go down",
      "we hit the 98% on-time target",
    ],
    userRoles: ["dispatcher", "driver", "warehouse lead", "customer success rep"],
    bugSymptoms: [
      "GPS drift in",
      "Duplicate scan events from",
      "Stale ETA shown on",
      "Crash on",
      "Sync conflict in",
      "Missing barcode parse in",
    ],
    bugSurfaces: [
      "driver app manifest screen",
      "scan-event ingest pipeline",
      "ETA widget",
      "dock-door scheduler",
      "POD photo upload",
    ],
    bugConditions: [
      "device loses connectivity mid-route",
      "two scanners read the same parcel",
      "the ETA model re-trains mid-day",
      "photo is larger than 8MB on a slow network",
      "timezone changes across a route leg",
    ],
    taskVerbs: ["Calibrate", "Backfill", "Audit", "Map", "Document", "Retire"],
    taskObjects: [
      "ETA model training windows",
      "scan-event dedupe rules",
      "dock-door capacity table",
      "carrier SLA catalog",
      "legacy telematics feed",
      "hazmat placarding rules",
    ],
    labels: ["routing", "driver-app", "eta", "warehouse", "telematics", "offline", "carrier"],
    commentSnippets: [
      "Field-tested on the Denver fleet — offline sync held up.",
      "The dedupe window needs ops sign-off before we tighten it.",
      "Model team confirmed the ETA drift is a data issue, not a code issue.",
      "Dispatcher pilot feedback attached to the ticket.",
    ],
    sprintGoals: ["Pilot dynamic re-routing in two regions", "Stabilize scan ingest dedupe"],
  },
};

// ─── Scenario meta ────────────────────────────────────────────────────────────

export interface ScenarioMeta {
  id: ScenarioId;
  label: string;
  blurb: string;
  icon: string; // lucide icon name resolved by caller
}

export const SCENARIOS: Record<ScenarioId, ScenarioMeta> = {
  scrum: {
    id: "scrum",
    label: "Scrum Software Project",
    blurb: "Sprints, epics, story points — a classic product team board",
    icon: "KanbanSquare",
  },
  kanban: {
    id: "kanban",
    label: "Kanban Service Team",
    blurb: "Flow-based ops work, WIP-heavy, few sprints",
    icon: "Columns3",
  },
  bugbash: {
    id: "bugbash",
    label: "Bug Bash / QA Cycle",
    blurb: "Bug-dense dataset with STR, severities and regressions",
    icon: "Bug",
  },
  servicedesk: {
    id: "servicedesk",
    label: "IT Service Desk",
    blurb: "Customer-style requests, incidents and SLA-ish priorities",
    icon: "Headset",
  },
  launch: {
    id: "launch",
    label: "Product Launch",
    blurb: "Cross-functional launch plan: marketing, eng, GTM tasks",
    icon: "Rocket",
  },
};
